# Generated by Django 5.1.5 on 2025-02-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sophia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('message', models.CharField(max_length=255)),
            ],
        ),
    ]
