# Generated by Django 5.1.5 on 2025-02-12 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sophia', '0004_rename_contactform_contactquery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contactquery',
            new_name='Contactquerys',
        ),
    ]
