# Generated by Django 5.1.5 on 2025-02-12 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sophia', '0005_rename_contactquery_contactquerys'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contactquerys',
        ),
    ]
