# Generated by Django 5.1.5 on 2025-02-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sophia', '0006_delete_contactquerys'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('message', models.CharField(max_length=255)),
            ],
        ),
    ]
