# Generated by Django 5.1.5 on 2025-02-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sophia', '0007_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
