# Generated by Django 5.1.5 on 2025-03-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sophia', '0009_jobapply'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapply',
            name='cover_letter',
            field=models.TextField(default='No cover letter attached'),
        ),
    ]
